const R=(window.RD||[]).map(x=>({ppd:x[0],school:x[1],program:x[2],purpose:x[3],date:x[4],vip:x[5],category:x[6],position:x[7],month:x[8],status:x[9]}));
const MONTHS=['Januari','Februari','Mac','April','Mei','Jun','Julai','Ogos','Tidak dinyatakan'];
const CATS=['ADUN','Ahli Parlimen','Ahli Parlimen & ADUN','Lain-lain','Tidak dinyatakan'];
const COLORS={'ADUN':'#43a65d','Ahli Parlimen':'#2f6bd8','Ahli Parlimen & ADUN':'#7d39cf','Lain-lain':'#f28c16','Tidak dinyatakan':'#7b8798'};
const $=id=>document.getElementById(id);const pct=(n,d)=>d?((n/d)*100).toFixed(1)+'%':'0%';const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const countBy=(arr,key)=>arr.reduce((o,r)=>{const k=r[key]||'Tidak dinyatakan';o[k]=(o[k]||0)+1;return o},{});const sortedCounts=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]);const unique=key=>[...new Set(R.map(r=>r[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ms'));let ppdChart,monthChart,catChart;
function fillSelect(id,vals){const el=$(id),first=el.options[0].outerHTML;el.innerHTML=first;vals.forEach(v=>{const op=document.createElement('option');op.value=v;op.textContent=v;el.appendChild(op)})}
fillSelect('ppdFilter',unique('ppd'));fillSelect('ppdZoom',unique('ppd'));fillSelect('monthFilter',MONTHS.filter(m=>R.some(r=>r.month===m)));fillSelect('catFilter',CATS.filter(c=>R.some(r=>r.category===c)));fillSelect('purposeFilter',unique('purpose'));
function filteredBase(){let a=R;const p=$('ppdFilter').value,m=$('monthFilter').value,c=$('catFilter').value,t=$('purposeFilter').value;if(p!=='ALL')a=a.filter(r=>r.ppd===p);if(m!=='ALL')a=a.filter(r=>r.month===m);if(c!=='ALL')a=a.filter(r=>r.category===c);if(t!=='ALL')a=a.filter(r=>r.purpose===t);return a}
function kpis(a){$('kTotal').textContent=a.length;$('kTotalPct').textContent=pct(a.length,R.length)+' daripada keseluruhan';CATS.forEach((c,i)=>{const n=a.filter(r=>r.category===c).length,ids=[['kAdun','pAdun'],['kMp','pMp'],['kBoth','pBoth'],['kOther','pOther'],['kMissing','pMissing']][i];$(ids[0]).textContent=n;$(ids[1]).textContent=pct(n,a.length)})}
function renderPurpose(a){const rows=sortedCounts(countBy(a,'purpose')).slice(0,7);$('purposeBody').innerHTML=rows.map(([k,n])=>`<tr><td>${esc(k)}</td><td>${n}</td><td>${pct(n,a.length)}</td></tr>`).join('');$('purposeTotal').textContent=a.length}
function initCharts(){monthChart=new Chart($('monthChart'),{type:'line',data:{labels:MONTHS.slice(0,8),datasets:[{data:[],borderColor:'#2f6bd8',backgroundColor:'rgba(47,107,216,.10)',fill:false,tension:.28,pointRadius:4,pointBackgroundColor:'#2f6bd8'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'#e7ecf3'}},x:{grid:{display:false}}}}});catChart=new Chart($('catChart'),{type:'doughnut',data:{labels:CATS,datasets:[{data:[],backgroundColor:CATS.map(c=>COLORS[c]),borderWidth:1,borderColor:'#fff'}]},options:{responsive:true,maintainAspectRatio:false,cutout:'58%',plugins:{legend:{position:'right',labels:{boxWidth:9,font:{size:10}}}}}});ppdChart=new Chart($('ppdChart'),{type:'bar',data:{labels:[],datasets:[{data:[],backgroundColor:'#356dc8',borderRadius:4}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,grid:{color:'#e7ecf3'}},y:{grid:{display:false},ticks:{font:{size:10}}}},onClick:(e,els)=>{if(!els.length)return;const p=ppdChart.data.labels[els[0].index];selectPpd(p,true)}}})}
function renderCharts(a){const mc=countBy(a,'month');monthChart.data.datasets[0].data=MONTHS.slice(0,8).map(m=>mc[m]||0);monthChart.update();const cc=countBy(a,'category');catChart.data.datasets[0].data=CATS.map(c=>cc[c]||0);catChart.update();const pc=sortedCounts(countBy(a,'ppd')).slice(0,10);ppdChart.data.labels=pc.map(x=>x[0]);ppdChart.data.datasets[0].data=pc.map(x=>x[1]);ppdChart.update()}
function renderAll(){const a=filteredBase();kpis(a);renderPurpose(a);renderCharts(a);syncZoomFromFilter()}
function ppdRecords(p){return filteredBase().filter(r=>r.ppd===p)}function schoolRecords(p,s){return ppdRecords(p).filter(r=>r.school===s)}
function updateSchoolOptions(){const p=$('ppdZoom').value,el=$('schoolZoom');el.innerHTML='<option value="ALL">Semua Sekolah / Institusi</option>';if(p==='ALL')return;sortedCounts(countBy(ppdRecords(p),'school')).forEach(([s])=>{const o=document.createElement('option');o.value=s;o.textContent=s;el.appendChild(o)})}
function legendHtml(a,key,items){const c=countBy(a,key);return items.map(k=>`<div class="legend-row"><div class="legend-left"><span class="sw" style="background:${COLORS[k]||'#6b7890'}"></span><span>${esc(k)}</span></div><strong>${c[k]||0} <span style="font-weight:500;color:#7b8798">(${pct(c[k]||0,a.length)})</span></strong></div>`).join('')}
function purposeHtml(a){return sortedCounts(countBy(a,'purpose')).slice(0,6).map(([k,n])=>`<div class="legend-row"><span>${esc(k)}</span><strong>${n} <span style="font-weight:500;color:#7b8798">(${pct(n,a.length)})</span></strong></div>`).join('')}
function selectPpd(p,scroll=false){$('ppdFilter').value=p;$('ppdZoom').value=p;updateSchoolOptions();$('schoolZoom').value='ALL';renderAll();renderDrill();if(scroll)$('drillSection').scrollIntoView({behavior:'smooth',block:'start'})}
function selectSchool(s){$('schoolZoom').value=s;renderDrill()}
function syncZoomFromFilter(){const p=$('ppdFilter').value;if($('ppdZoom').value!==p){$('ppdZoom').value=p;updateSchoolOptions();$('schoolZoom').value='ALL'}renderDrill()}
function renderDrill(){const p=$('ppdZoom').value,s=$('schoolZoom').value;$('zSabah').classList.toggle('active',p==='ALL');$('zPpd').classList.toggle('active',p!=='ALL'&&s==='ALL');$('zSchool').classList.toggle('active',s!=='ALL');$('zPpdText').textContent=p==='ALL'?'PPD':p+' (PPD)';$('zSchoolText').textContent=s==='ALL'?'Sekolah':s+' (Sekolah)';$('crumbPpd').textContent=p==='ALL'?'Pilih PPD':p;$('crumbSchool').style.display=s==='ALL'?'none':'inline-block';$('crumbSep').style.display=s==='ALL'?'none':'inline';$('crumbSchool').textContent=s;if(p==='ALL'){$('schoolInfo').innerHTML='Pilih PPD untuk melihat sekolah.';$('schoolCount').textContent='—';$('schoolCat').innerHTML='<div class="empty">Belum ada sekolah dipilih.</div>';$('schoolPurpose').innerHTML='<div class="empty">Belum ada sekolah dipilih.</div>';$('schoolRank').innerHTML='';$('rankTitle').textContent='10 SEKOLAH TERATAS';$('detailsBox').style.display='none';return}const pr=ppdRecords(p),ranks=sortedCounts(countBy(pr,'school')).slice(0,10);$('rankTitle').textContent='10 SEKOLAH TERATAS DI '+p.toUpperCase();$('schoolRank').innerHTML=ranks.map(([name,n],i)=>`<tr class="rank-row ${s===name?'active':''}" data-school="${esc(name)}"><td>${i+1}. &nbsp; ${esc(name)}</td><td>${n}</td></tr>`).join('');document.querySelectorAll('[data-school]').forEach(x=>x.onclick=()=>selectSchool(x.dataset.school));if(s==='ALL'){$('schoolInfo').innerHTML=`PPD: <strong>${esc(p)}</strong><br>Jumlah sekolah/institusi: <strong>${Object.keys(countBy(pr,'school')).length}</strong><br>Jumlah permohonan: <strong>${pr.length}</strong>`;$('schoolCount').textContent=pr.length;$('schoolCat').innerHTML=legendHtml(pr,'category',CATS);$('schoolPurpose').innerHTML=purposeHtml(pr);$('detailsBox').style.display='none';return}const sr=schoolRecords(p,s);$('schoolCount').textContent=sr.length;$('schoolInfo').innerHTML=`PPD: <strong>${esc(p)}</strong><br>Sekolah: <strong>${esc(s)}</strong><br>Jumlah Permohonan: <strong>${sr.length}</strong><br>% daripada PPD: <strong>${pct(sr.length,pr.length)}</strong>`;$('schoolCat').innerHTML=legendHtml(sr,'category',CATS);$('schoolPurpose').innerHTML=purposeHtml(sr);$('detailsBox').style.display='block';$('detailsTitle').textContent=`PERINCIAN PERMOHONAN - ${s.toUpperCase()} (${p.toUpperCase()})`;$('detailsBody').innerHTML=sr.length?sr.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${esc(r.date)}</strong></td><td>${esc(r.program)}</td><td>${esc(r.purpose)}</td><td><strong>${esc(r.vip)}</strong></td><td>${esc(r.position)}</td><td><span class="cat-badge cat-${r.category==='ADUN'?'ADUN':r.category.startsWith('Ahli Parlimen &')?'AP':r.category.startsWith('Ahli')?'Ahli':'Lain'}">${esc(r.category)}</span></td><td>${esc(r.status)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">Tiada rekod.</td></tr>'}
$('ppdFilter').onchange=()=>{const p=$('ppdFilter').value;$('ppdZoom').value=p;updateSchoolOptions();$('schoolZoom').value='ALL';renderAll()};$('monthFilter').onchange=renderAll;$('catFilter').onchange=renderAll;$('purposeFilter').onchange=renderAll;$('ppdZoom').onchange=()=>{const p=$('ppdZoom').value;$('ppdFilter').value=p;updateSchoolOptions();$('schoolZoom').value='ALL';renderAll()};$('schoolZoom').onchange=renderDrill;$('resetAll').onclick=$('backAll').onclick=()=>{$('ppdFilter').value='ALL';$('monthFilter').value='ALL';$('catFilter').value='ALL';$('purposeFilter').value='ALL';$('ppdZoom').value='ALL';updateSchoolOptions();$('schoolZoom').value='ALL';renderAll()};$('crumbSabah').onclick=$('backAll').onclick;$('crumbPpd').onclick=()=>{$('schoolZoom').value='ALL';renderDrill()};initCharts();renderAll();